//
//  CollageManager.swift
//  PhoneAddictionMugshot
//
//  Created by Conflux Solutions LLC
//  Copyright © 2026 Conflux Solutions LLC. All rights reserved.
//

import UIKit

class CollageManager {
    static let shared = CollageManager()
    
    private init() {}
    
    func createCollage(from images: [UIImage], title: String = "Phone Addiction MUGSHOT") -> UIImage? {
        guard !images.isEmpty else { return nil }
        
        // Configuration
        let spacing: CGFloat = 20
        let targetWidth: CGFloat = 1080 // Standard social media width
        let headerHeight: CGFloat = 120
        let footerHeight: CGFloat = 80
        
        // Calculate grid layout
        let count = images.count
        let columns = Int(ceil(sqrt(Double(count))))
        let rows = Int(ceil(Double(count) / Double(columns)))
        
        let itemWidth = (targetWidth - (spacing * CGFloat(columns + 1))) / CGFloat(columns)
        // Assume square items for simplicity, or fit to content
        let itemHeight = itemWidth * 1.33 // 4:3 aspect ratio per mugshot usually looks good
        
        let gridHeight = (itemHeight * CGFloat(rows)) + (spacing * CGFloat(rows + 1))
        let totalHeight = headerHeight + gridHeight + footerHeight
        
        let size = CGSize(width: targetWidth, height: totalHeight)
        
        let renderer = UIGraphicsImageRenderer(size: size)
        
        return renderer.image { context in
            // Background
            UIColor(red: 0.1, green: 0.1, blue: 0.1, alpha: 1.0).setFill()
            context.fill(CGRect(origin: .zero, size: size))
            
            // Header
            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 48, weight: .heavy),
                .foregroundColor: UIColor.white
            ]
            let titleSize = (title as NSString).size(withAttributes: titleAttrs)
            (title as NSString).draw(at: CGPoint(x: (targetWidth - titleSize.width) / 2, y: 40), withAttributes: titleAttrs)
            
            // Grid
            for (index, image) in images.enumerated() {
                let row = index / columns
                let col = index % columns
                
                let x = spacing + CGFloat(col) * (itemWidth + spacing)
                let y = headerHeight + spacing + CGFloat(row) * (itemHeight + spacing)
                
                let rect = CGRect(x: x, y: y, width: itemWidth, height: itemHeight)
                
                // Draw rounded rect clip
                let path = UIBezierPath(roundedRect: rect, cornerRadius: 12)
                path.addClip()
                image.draw(in: rect)
                
                // Reset clip
                context.cgContext.resetClip()
                
                // Draw border
                UIColor.white.withAlphaComponent(0.2).setStroke()
                path.lineWidth = 2
                path.stroke()
            }
            
            // Footer
            let footerText = "Generated by PhoneAddictionMugshot"
            let footerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 24, weight: .medium),
                .foregroundColor: UIColor.lightGray
            ]
            let footerSize = (footerText as NSString).size(withAttributes: footerAttrs)
            (footerText as NSString).draw(at: CGPoint(x: (targetWidth - footerSize.width) / 2, y: totalHeight - 50), withAttributes: footerAttrs)
        }
    }
}
